### ISSUE TITLE
Wrong class registered in jaxrs feature

### ISSUE THREAD

**Issue by zenios** [apache/shiro#1383]
https://github.com/apache/shiro/blob/75123583017b3c9091e99e44775046ed5b3c4a3a/support/jaxrs/src/main/java/org/apache/shiro/web/jaxrs/ShiroFeature.java#L60

It should be UnauthenticatedExceptionExceptionMapper not UnauthenticatedException

**Comment by steinarb** [comment]
There may still be something wrong with this...?

I tried the current main snapshot today and my unit tests were flipped: The test expecting status code 401 got 403 and the test expecting status code 403 got 401.

I tried the snapshot since I got failing unit tests when using  shiro 2.0.0: https://lists.apache.org/thread/fwslydgdtnscv5tg6yqgnx88zdl50gco

With shiro 2.0.0 I got 401 Unauthorized responses where I was expecting 403 Forbidden (accessing rest endpoint with a logged in user without the required role) and I got UnauthenticatedException where I was expecting a 401 Unauthorized response.

But with a snapshot built from the current main I no longer got UnauthenticatedException, but the tests expected 401 and 403 status code got unexpected results (the actual values of the tests were flipped wrt the expected values).

- This is the test expecting 401 and getting 403: https://github.com/steinarb/servlet/blob/master/servlet/servlet.jersey/src/test/java/no/priv/bang/servlet/jersey/JerseyServletTest.java#L127
- This is the test expecting 403 and getting 401: https://github.com/steinarb/servlet/blob/master/servlet/servlet.jersey/src/test/java/no/priv/bang/servlet/jersey/JerseyServletTest.java#L147

Here is the shiro-jaxrs annotated jersey resource used by the tests: https://github.com/steinarb/servlet/blob/master/servlet/servlet.jersey/src/test/java/no/priv/bang/servlet/jersey/test/resources/ProtectedHelloResource.java#L13

Here is the shiro.ini file defining the users and role used by the tests: https://github.com/steinarb/servlet/blob/master/servlet/servlet.jersey/src/test/resources/test.shiro.ini
