### ISSUE TITLE
Issue templates missing

### ISSUE THREAD

**Issue by bmarwell** [apache/shiro#897]
We need an issue template now that we have GitHub issues open.
This could get us started:
https://gist.github.com/bjankord/0db8add11881ba4ba8003ece82561f76

We should include

- [ ] here is not the place to report security issues
- [ ] expected / actual behaviour (if it is a bug)
- [ ] ...?

**Comment by fpapon** [comment]
We have this in another ASF project:

https://github.com/apache/eventmesh/tree/master/.github/ISSUE_TEMPLATE

I think we can reuse it

**Comment by EdgarRamirezFuentes** [comment]
Hi! 😄 
I'm new in this world of Open Source contributions, and I think this could be my good first issue.
May I help you adding the issue templates for this project?

**Comment by lprimak** [comment]
Sure!  All help is appreciated

**Comment by EdgarRamirezFuentes** [comment]
Thanks! 
I added new issue templates based on the eventmesh templates mentioned before.
I did not add the unit testing template because I did not find any info about it in the website.

<img width="1147" alt="Captura de pantalla 2023-07-05 a la(s) 14 35 22" src="https://github.com/apache/shiro/assets/50359137/389cd9ff-97a0-4706-86c8-514474c3058f">
